### ISSUE TITLE
peewee backend, error on adding resource

### ISSUE THREAD

**Issue by KhodeN** [biosustain/potion#52] opened 2015-11-29 04:25 UTC
```python
from flask import Flask
from flask_potion import Api, ModelResource
from flask_potion.backends.peewee import PeeweeManager
import peewee as pw

app = Flask(__name__)
app.config['DEBUG'] = True
api = Api(app, default_manager=PeeweeManager)

db = pw.PostgresqlDatabase('profood', user='postgres')


class Goods(pw.Model):
    matrix = pw.CharField(max_length=13)
    name = pw.CharField(max_length=256)
    description = pw.TextField()

    class Meta:
        database = db


class GoodResource(ModelResource):
    class Meta:
        model = Goods

api.add_resource(GoodResource)

if __name__ == "__main__":
    app.run()
```

returns error

```
Traceback (most recent call last):
  File "/home/tema/projects/profood/testArea/backend/fail.py", line 26, in <module>
    api.add_resource(GoodResource)
  File "/home/tema/.pyenv/versions/profood/lib/python3.5/site-packages/flask_potion/__init__.py", line 157, in add_resource
    resource.manager = self.default_manager(resource, resource.meta.get('model'))
  File "/home/tema/.pyenv/versions/profood/lib/python3.5/site-packages/flask_potion/backends/peewee.py", line 63, in __init__
    for name, column in model._meta.get_sorted_fields():
AttributeError: 'ModelOptions' object has no attribute 'get_sorted_fields'
```

**Comment by kolanos** [comment] 2015-11-29 16:56
I don't believe Potion is being tested on Python 3.5. What version of Peewee are you using?

**Comment by lyschoening** [comment] 2015-11-29 17:43
The issue is a regression with peewee 2.7.x. It's fixed in master already. I will release an update soon. Meanwhile, downgrading to peewee 2.6 or installing from master will resolve the issue.

**Closed by lyschoening** 2015-11-29 17:43 UTC
